services:
  lms-app:
    build:
      context: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - app-network
  lms-tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - app

networks:
  app-network: